#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
elif [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

set -x

${PREFIX}pytest --cov-report term-missing --cov-report=xml:coverage.xml --cov=dam tests/
${PREFIX}black dam tests --check
${PREFIX}flake8 --max-line-length=88 dam/ tests/
